appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: NtHQB4pQYNBMvNKKy1L1gzn0WHOw4Gi/gAakZ41EB1paQ5lYlCXzbvWfdtADiCsHvl+BDYvy22MWoZvKqs3+DGF0CedW51/gEs/EkCZNLfFlRSKi1B/mx26vWro3OvmvyKkRnXfDXuicwiOJVDwmD+dfRUXP3CJkYIkbROoIS09fRb4uyVW9h6/HiT1lDfogAnK3soyOOBn7lGBCBNG6bZ16HR1oOTBsNgHzsuZKKK1cSaCgiYBeGCOiYqPfJXq6ddvhVYrTW5Nuhu2uaFqacabJKjoamFYchHb6U5Ex1imr9FlvGDpbRyKIz4DJhXf3MC7MACLh7socbsTutE+4L3pKPiFNVJa38AnUQ3rA1XAjaeIn4uNiCV7LTqL/63sh1PponM8k8UP3wz9YevJlW1oGd7bXgtr/6CsY/d47ZjzhVY7mlhLA64RO1IQICYq46LVg8pq7pqE/SLzSro6rD1bTHhC/K/fXEUpBh2jVkmbzszFi1Yw19ddyY8f9S0NcSg4YZVMGqW1mkO2Ff00RODaxm/L+YAp4sefzTRhlN7Ik3sQ71GgdXjT+OS81zwWvnPvz0UMsKA3juTMdcWmABEB7h+Jmg0QY/Y2cRYFwERxNCghppX+WZh49jAsa4Yr51MESES0/nw8bAzOkY7Jgw+imDrc/fHHz6YcFOLWXY6U=
conda_forge_output_validation: true
